#!/usr/bin/env bash
set -e
apt-get update && apt-get install -y dnsutils shellcheck  # git rsync
command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )
mkdir -p ~/.ssh
chmod 700 ~/.ssh
echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
chmod 644 ~/.ssh/known_hosts
